"""Builds the interactive HTML dashboard and the automated markdown report."""
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from .config import *

fmt = lambda v: f"₹{v/1e7:.2f} Cr" if v >= 1e7 else f"₹{v/1e5:.2f} L" if v >= 1e5 else f"₹{v:,.0f}"


def kpis(clean, fc, cust):
    s = clean.copy(); s["year"] = s["date"].dt.year
    yr = s.groupby("year")["sales"].sum()
    last, prev = yr.index.max(), yr.index.max() - 1
    store = s[s["year"] == last].groupby(["store_id", "store_type", "region", "size_sqft"])["sales"].sum().reset_index()
    store["sales_per_sqft"] = store["sales"] / store["size_sqft"]
    promo = s[s["year"] == last].groupby("promo")["sales"].mean()
    conv = (s["transactions"].sum() / s["footfall"].sum()) if "footfall" in s else np.nan
    return dict(last=last, sales_last=yr[last], yoy=(yr[last] / yr[prev] - 1) * 100, store=store, promo_uplift=(promo[1] / promo[0] - 1) * 100,
                conv=conv, region=s[s["year"] == last].groupby("region")["sales"].sum().sort_values(ascending=False),
                stype=s[s["year"] == last].groupby("store_type")["sales"].sum(), yearly=yr,
                churn_rate=cust["churned"].mean() * 100, high_risk=(cust["risk"] == "High").sum(),
                rev_at_risk=cust.loc[cust["risk"] == "High", "monetary_12m"].sum(), fc_total=fc["forecast"].sum())


def build_dashboard(clean, F, C, S, K):
    daily = clean.groupby("date")["sales"].sum()
    fcd = F["forecast"].groupby("date")["forecast"].sum()
    predd = F["pred"].groupby("date")[["sales", "pred_gbm"]].sum()
    fig = make_subplots(rows=4, cols=2, vertical_spacing=.08, specs=[[{"colspan": 2}, None], [{}, {}], [{}, {}], [{}, {}]],
        subplot_titles=("Chain daily sales: history, 2023 backtest and 28-day forecast", "Top / bottom stores by sales per sq ft",
                        "Sales by region", "Forecast drivers (permutation importance)", "Churn risk distribution",
                        "Customer segments: share of 12m revenue %", "Churn drivers (permutation importance)", "Monthly sales by year"))
    w = daily.rolling(7).mean()
    fig.add_trace(go.Scatter(x=w.index, y=w, name="7-day avg actual", line=dict(color="#1f77b4")), 1, 1)
    fig.add_trace(go.Scatter(x=predd.index, y=predd["pred_gbm"].rolling(7).mean(), name="2023 backtest", line=dict(color="orange", dash="dot")), 1, 1)
    fig.add_trace(go.Scatter(x=fcd.index, y=fcd.values, name="28-day forecast", line=dict(color="red", width=3)), 1, 1)
    st = K["store"].sort_values("sales_per_sqft"); sel = pd.concat([st.head(5), st.tail(5)])
    fig.add_trace(go.Bar(x=sel["sales_per_sqft"], y=sel["store_id"], orientation="h", marker_color=["#d62728"] * 5 + ["#2ca02c"] * 5, showlegend=False), 2, 1)
    fig.add_trace(go.Bar(x=K["region"].index, y=K["region"].values, showlegend=False, marker_color="#6a5acd"), 2, 2)
    imp = F["importance"].head(10)[::-1]; fig.add_trace(go.Bar(x=imp.values, y=imp.index, orientation="h", showlegend=False, marker_color="#17becf"), 3, 1)
    rc = C["scored"]["risk"].value_counts().reindex(["Low", "Medium", "High"])
    fig.add_trace(go.Bar(x=rc.index.astype(str), y=rc.values, showlegend=False, marker_color=["#2ca02c", "#ff7f0e", "#d62728"]), 3, 2)
    pr = S["profile"]; fig.add_trace(go.Bar(x=pr.index, y=pr["revenue_share_%"], showlegend=False, marker_color="#8c564b"), 4, 1)
    ci = C["importance"].head(8)[::-1]; fig.add_trace(go.Bar(x=ci.values, y=ci.index, orientation="h", showlegend=False, marker_color="#e377c2"), 4, 2)
    fig.update_layout(height=1500, template="plotly_white", margin=dict(t=170),
        title=dict(text=(f"<b>Advanced Business Analytics Dashboard</b><br><sup>{K['last']} sales {fmt(K['sales_last'])} ({K['yoy']:+.1f}% YoY) · "
                         f"Promo uplift {K['promo_uplift']:+.0f}% · Next-28d forecast {fmt(K['fc_total'])} · Forecast MAPE {F['table'].loc[F['best'],'MAPE_%']:.1f}% · "
                         f"Churn {K['churn_rate']:.0f}% · High-risk customers {K['high_risk']:,} ({fmt(K['rev_at_risk'])} revenue at risk)</sup>"), x=.01))
    fig.write_html(OUT / "interactive_dashboard.html", include_plotlyjs="cdn")


def build_report(log, clog, F, C, S, K, clean):
    t, ct = F["table"], C["table"]; best = F["best"]
    base = t.loc["Seasonal naive (same weekday, 4 wks ago)", "MAE"]
    gain = (1 - t.loc[best, "MAE"] / base) * 100
    st = K["store"].sort_values("sales_per_sqft"); top, bot = st.iloc[-1], st.iloc[0]
    prof = S["profile"]
    md = f"""# Advanced Business Analytics System - Predictive Insights Report
*Auto-generated by `run_pipeline.py` on {pd.Timestamp.today():%d %b %Y}. Data: {clean['date'].min():%b %Y} - {clean['date'].max():%b %Y}, {clean['store_id'].nunique()} stores.*

## 1. Executive summary
* {K['last']} chain sales were **{fmt(K['sales_last'])}** ({K['yoy']:+.1f}% vs previous year).
* Promotion days sell **{K['promo_uplift']:+.0f}%** more per store-day than non-promo days.
* The best model ({best}) forecasts store sales 28 days ahead with **{t.loc[best,'MAPE_%']:.1f}% MAPE** (R² {t.loc[best,'R2']:.2f}), cutting MAE by **{gain:.0f}%** versus the seasonal-naive baseline.
* Expected chain sales for the next 28 days: **{fmt(K['fc_total'])}**.
* {K['churn_rate']:.0f}% of customers churned; the churn model flags **{K['high_risk']:,} high-risk customers** carrying {fmt(K['rev_at_risk'])} of 12-month spend.

## 2. Data preparation
| Step | Result |
|---|---|
| Raw store-day rows | {log['raw_rows']:,} |
| Duplicate store-days removed | {log['duplicates_removed']} |
| Negative sales set to missing | {log['negative_sales']} |
| Keying-error outliers (> 4x rolling median) removed | {log['outliers_removed']} |
| Missing sales imputed (per-store interpolation) | {log['missing_sales_imputed']} |
| Missing temperature imputed | {log['missing_temp_imputed']} |
| Clean rows | {log['clean_rows']:,} |

Feature engineering: calendar (weekday, month, week, cyclical day-of-year), holiday proximity, promo flag, temperature, store attributes, lags (28/35/42/364 days) and rolling mean/std computed on data at least 28 days old, so the model only uses information available when the forecast is made.

## 3. Sales forecasting (test = year 2023, train = earlier years, time-ordered split)
{t.to_markdown()}

Best hyper-parameters: `{F['best_params']}`. Top drivers: {', '.join(F['importance'].head(5).index)}.

## 4. KPIs ({K['last']})
* Best store by sales per sq ft: **{top['store_id']}** ({top['store_type']}, {top['region']}) at ₹{top['sales_per_sqft']:,.0f}; weakest: **{bot['store_id']}** ({bot['store_type']}, {bot['region']}) at ₹{bot['sales_per_sqft']:,.0f}.
* Top region: **{K['region'].index[0]}** ({K['region'].iloc[0]/K['region'].sum()*100:.0f}% of sales). Store types: {', '.join(f'{k} {v/K["stype"].sum()*100:.0f}%' for k, v in K['stype'].items())}.
* Footfall-to-transaction conversion: {K['conv']*100:.0f}%.

## 5. Customer behaviour
### Churn prediction (hold-out 25%, {C['test_n']:,} customers; threshold 0.35)
{ct.to_markdown()}

Selected production model: **{C['best']}** (highest ROC-AUC).

Top-decile lift: the 10% highest-scored customers churn **{C['lift']:.1f}x** more often than average. Main drivers: {', '.join(C['importance'].head(4).index)}.

### Segments (K-Means, k={S['k']} chosen by silhouette)
{prof[['customers','recency','frequency','monetary','promo_share','churn_rate','revenue_share_%']].to_markdown()}

## 6. Predictive recommendations
1. **Inventory & staffing:** use the 28-day store-level forecast (`outputs/forecast_next_28d.csv`) for replenishment and rostering; peak days follow weekends, promo windows and festivals.
2. **Promotions:** with a {K['promo_uplift']:+.0f}% lift, concentrate campaigns on weak-performing stores ({bot['store_id']} and similar) and avoid discounting already high-demand festival days.
3. **Retention:** launch win-back offers for the {K['high_risk']:,} high-risk customers, starting with the highest-spend ones (`outputs/customers_scored.csv`).
4. **Segments:** protect "High-value regulars" with loyalty benefits; grow basket size of "Low-spend occasional" shoppers with cross-sell bundles and targeted, margin-aware coupons.
5. **Store performance:** investigate the bottom-5 stores by sales per sq ft (layout, assortment, local competition) and replicate practices from the top stores.
6. **Retraining:** re-run `python run_pipeline.py` weekly (a GitHub Actions workflow is included) to refresh data, models, dashboard and this report.

## 7. Limitations
Data is synthetic (see `src/data_generation.py`); metrics demonstrate the methodology, not real-world accuracy. Future promotions are assumed to follow the chain-wide campaign calendar; store-specific promos are unknown in advance.
"""
    (REPORTS / "predictive_insights_report.md").write_text(md)


def static_charts(clean, F, C, S):
    import matplotlib; matplotlib.use("Agg")
    import matplotlib.pyplot as plt, seaborn as sns
    sns.set_theme(style="whitegrid")
    def save(fig, n): fig.tight_layout(); fig.savefig(CHARTS / n, dpi=140); plt.close(fig)
    p = F["pred"].groupby("date")[["sales", "pred_gbm"]].sum()
    fc = F["forecast"].groupby("date")["forecast"].sum()
    hist = clean.groupby("date")["sales"].sum().iloc[-90:]
    fig, ax = plt.subplots(figsize=(12, 4.5)); ax.plot(hist.index, hist / 1e5, label="Actual daily sales")
    ax.plot(p.index[-90:], p["pred_gbm"].iloc[-90:] / 1e5, "--", color="orange", label="Model backtest (unseen 2023 data)")
    ax.plot(fc.index, fc.values / 1e5, color="red", lw=2.2, label="28-day forecast")
    ax.axvline(hist.index[-1], color="gray", ls=":"); ax.set(title="Chain daily sales: last 90 days, backtest and next-28-day forecast", ylabel="₹ lakh"); ax.legend(loc="upper left")
    save(fig, "01_forecast.png")
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.2))
    t = F["table"]; axes[0].barh(t.index, t["MAPE_%"], color=["#999", "#6baed6", "#2ca02c"]); axes[0].set_title("Forecast error (MAPE %) - lower is better")
    imp = F["importance"].head(10)[::-1]; axes[1].barh(imp.index, imp.values, color="#17becf"); axes[1].set_title("Forecast drivers (permutation importance)")
    save(fig, "02_forecast_models_importance.png")
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.2))
    ci = C["importance"].head(8)[::-1]; axes[0].barh(ci.index, ci.values, color="#e377c2"); axes[0].set_title("Churn drivers (AUC drop)")
    rc = C["scored"]["risk"].value_counts().reindex(["Low", "Medium", "High"]); axes[1].bar(rc.index.astype(str), rc.values, color=["#2ca02c", "#ff7f0e", "#d62728"]); axes[1].set_title("Customers by churn risk")
    save(fig, "03_churn.png")
    pr = S["profile"]; fig, axes = plt.subplots(1, 2, figsize=(12, 4.2))
    axes[0].bar(pr.index, pr["customers"], color="#4c72b0"); axes[0].set_title("Customers per segment"); axes[0].tick_params(axis="x", rotation=15)
    axes[1].bar(pr.index, pr["revenue_share_%"], color="#55a868"); axes[1].set_title("Revenue share % per segment"); axes[1].tick_params(axis="x", rotation=15)
    save(fig, "04_segments.png")
